[toc]





## Hints and tips

### Learning

- 
- On other texts that are highly interesting, well written, highly useful, or highly important, your curiosity and rage to master may kick in and let you go on for several hours without a break.
-  In [incremental reading](https://help.supermemo.org/wiki/Glossary:Incremental_reading), the primary criterion for time allocation is your level of concentration. You can literally lick a hundred articles in a continuous block of time and still keep your mind highly focused and alert. Some articles will be processed in depth, others will be quickly postponed. The concentration criterion is all-inclusive. It includes all factors listed above: difficulty of an article may affect your concentration, your tiredness will always reduce optimum allocations for difficult texts and increase allocations for interesting or enjoyable texts (those who help you "survive" a bad learning day)
- **You can leave some low-priority material in the passive form** (i.e. without generating [cloze deletions](https://help.supermemo.org/wiki/Glossary:Cloze_deletion)). Naturally, this material will gradually become difficult to recall or entirely forgotten. The best moment for using **Remember cloze** is when you notice that the material becomes volatile. Do not convert the entire passage into [clozes](https://help.supermemo.org/wiki/Glossary:Cloze_deletion) at once (unless it is very important). Pick the most important keyword and create just a single [cloze deletion](https://help.supermemo.org/wiki/Glossary:Cloze_deletion). When the next review of the passage comes along, you will be able to determine which other keywords must be used with [cloze deletion](https://help.supermemo.org/wiki/Glossary:Cloze_deletion) to prevent forgetting the key information. It is very difficult to predict how many [clozes](https://help.supermemo.org/wiki/Glossary:Cloze_deletion) you will need to generate to attain perfect recall of the whole passage. On occasion, a single [cloze](https://help.supermemo.org/wiki/Glossary:Cloze_deletion) suffices. At other times, a single passage can require a dozen of [clozes](https://help.supermemo.org/wiki/Glossary:Cloze_deletion)!
- **The better you get, the more often you will want to resort to incremental learning**. The stronger your incremental learning skills, the shorter the working period that makes employing incremental learning effective. For a proficient user, even a next day's assignment might make sense to be done with incremental learning tools. For a beginner though, it is enough to consider that it may take you a few months of practise to truly understand the flow of knowledge in incremental reading (and in your memory). This alone might make it ineffective in learning for a test that comes in a month or two
- **[Auto-postpone](https://help.supermemo.org/wiki/Glossary:Auto-postpone)** brings you closer to the ideal spaced repetition learning by reducing the load of low priority material that you cannot possibly master due to excess volume. In a sense, [auto-postpone](https://help.supermemo.org/wiki/Glossary:Auto-postpone) separates high priority material ([spaced repetition](https://help.supermemo.org/wiki/Glossary:Spaced_repetition)) and low priority material (traditional learning). Without it, you are stuck in the middle of those two extremes
- You can **increase the randomization of your material** by adding to **Randomization** degree in [sorting criteria](https://help.supermemo.org/wiki/Priority_queue#Sorting_repetitions) (**[Learn](https://help.supermemo.org/wiki/Learn_menu) : [Sorting](https://help.supermemo.org/wiki/Learn_menu#Sorting) : Sorting criteria** from the [main menu](https://help.supermemo.org/wiki/Main_menu)). Randomization can be set separately for [topics](https://help.supermemo.org/wiki/Glossary:Topic) and [items](https://help.supermemo.org/wiki/Glossary:Item). It should help you avoid tunnel vision and the [priority bias](https://help.supermemo.org/wiki/Priority_queue#Priority_bias_in_incremental_reading)
- **You can shorten or increase the [interval](https://help.supermemo.org/wiki/Glossary:Interval) for individual [elements](https://help.supermemo.org/wiki/Glossary:Element)**. If you want to schedule a given article for review on a selected day, choose **[Learning](https://help.supermemo.org/wiki/Element_menu#Learning) : [Reschedule](https://help.supermemo.org/wiki/Element_menu#Jump_interval)** on the [element menu](https://help.supermemo.org/wiki/Element_menu) (e.g. by pressing *Ctrl+J*). You can also use **[Learning](https://help.supermemo.org/wiki/Element_menu#Learning) : [Execute repetition](https://help.supermemo.org/wiki/Element_menu#Execute_repetition)** (e.g. by pressing *Ctrl+Shift+R*). **Execute repetition** works like **Reschedule** with this difference that a repetition will be executed before rescheduling. Choose between the two depending on whether you have seen the contents of the [item](https://help.supermemo.org/wiki/Glossary:Item) and have attempted to recall it from memory. **Execute repetition** requires providing a grade (unless you execute it on day when a repetition has already been done).
- **For [items](https://help.supermemo.org/wiki/Glossary:Item) of lesser importance, reduce [priority](https://help.supermemo.org/wiki/Glossary:Priority)** (*Alt+P*), increase the [interval](https://help.supermemo.org/wiki/Glossary:Interval) (*Ctrl+Shift+R*), or even increase the [forgetting index](https://help.supermemo.org/wiki/Glossary:Forgetting_index). Forgetting index can be used to optimize the trade-off between the [knowledge acquisition rate](https://help.supermemo.org/wiki/Glossary:Acquisition_rate) and [knowledge retention](https://help.supermemo.org/wiki/Glossary:Retention). Giving [items](https://help.supermemo.org/wiki/Glossary:Item) low [priority](https://help.supermemo.org/wiki/Glossary:Priority) in an overloaded [collection](https://help.supermemo.org/wiki/Glossary:Collection) is similar to giving it a higher [forgetting index](https://help.supermemo.org/wiki/Glossary:Forgetting_index).
- The degree of **damage incurred by material overload** can be seen in **[Toolkit](https://help.supermemo.org/wiki/Toolkit_menu) : [Statistics](https://help.supermemo.org/wiki/Toolkit_menu#Statistics) : [Analysis](https://help.supermemo.org/wiki/Analysis) : [Use](https://help.supermemo.org/wiki/Analysis#Use) : Priority protection**. On one hand you want to increase the value of **Priority protection**. On the other, limiting the speed of importing new articles in proportion to the progress of learning might make your [collection](https://help.supermemo.org/wiki/Glossary:Collection) "get stale" resulting in less fun in learning and lesser motivation. Some older articles may be pushed away to lower [priorities](https://help.supermemo.org/wiki/Glossary:Priority) by [overload](https://help.supermemo.org/wiki/Glossary:Overload) only to be deleted later as not important enough, not good enough, or outdated
- You should never stop thinking about **the value of [items](https://help.supermemo.org/wiki/Glossary:Item) that you keep in your memory**. See: [Re-evaluation of items](https://help.supermemo.org/wiki/Incremental_learning#Re-evaluation_of_items)
- Use **[Learning](https://help.supermemo.org/wiki/Browser_menu#Learning) : Spread** in the [browser](https://help.supermemo.org/wiki/Browser) to **change the distribution of your learning material in time**. You can speed up learning before an exam by compressing your learning schedule in a selected period. You can also redistribute the material in a longer period after a boring exam (for incremental review, re-learning, deprioritization, and/or elimination). For that latter job, you can choose a specific portion of the material to be served per day. Read about **[Mercy](https://help.supermemo.org/wiki/Mercy)**
- **Derivation steps in reasoning/mathematics**. If you are learning mathematics, you might wonder if you should commit individual derivation steps of a mathematic proof or solution, or should you just focus on the final outcome. The choice will depend on your goals. If you only need the final formula, time spent on learning the derivation steps could be better spent learning other important portions of the material. If you are not sure today what you will need in the future, you could just type in the whole derivation into a single [topic](https://help.supermemo.org/wiki/Glossary:Topic) and memorize the final formula. Later, in [incremental reading](https://help.supermemo.org/wiki/Glossary:Incremental_reading), you will make incremental decisions whether portions of the derivation are or are not important in your work or further learning. This piece of knowledge will compete with others in the learning process and in the long term you may ultimately decide if you want to memorize the details, keep them for [passive review](https://help.supermemo.org/wiki/Glossary:Passive_review) only, [dismiss](https://help.supermemo.org/wiki/Glossary:Dismiss)/delete some of the steps, or [dismiss](https://help.supermemo.org/wiki/Glossary:Dismiss) the entire derivation as redundant (or too costly to learn). Naturally, derivation will often enhance your ability to efficiently use the formula. Hence the decision is never easy. Once you have derivation steps committed, you can always play with their [priority](https://help.supermemo.org/wiki/Glossary:Priority) to determine the probability you will review them well enough to make a difference to your knowledge.
- **You can separate reading ([topic](https://help.supermemo.org/wiki/Glossary:Topic)) from review ([items](https://help.supermemo.org/wiki/Glossary:Item))**. However, variety is a spice of life. A random mix of reading and repetitions is a very powerful tool in overcoming the monotony of the earlier versions of SuperMemo. Interspersing [topics](https://help.supermemo.org/wiki/Glossary:Topic) with [items](https://help.supermemo.org/wiki/Glossary:Item) provides for many of the advantages of [incremental reading](https://help.supermemo.org/wiki/Glossary:Incremental_reading) as opposed to traditional learning or classical SuperMemo. To review [topics](https://help.supermemo.org/wiki/Glossary:Topic) only (reading) choose (1) **[View](https://help.supermemo.org/wiki/View_menu) : [Outstanding](https://help.supermemo.org/wiki/View_menu#Outstanding)**, (2) **[Child](https://help.supermemo.org/wiki/Browser_menu#Child) : Topics** and then (3) **[Process browser>](https://help.supermemo.org/wiki/Subset_operations) : [Learning](https://help.supermemo.org/wiki/Subset_operations#Learning) : [Learn](https://help.supermemo.org/wiki/Subset_learning)** (*Ctrl+L*). To make repetitions only ([items](https://help.supermemo.org/wiki/Glossary:Item)), use an analogous method. It might be a better strategy to mix [topics](https://help.supermemo.org/wiki/Glossary:Topic) and [items](https://help.supermemo.org/wiki/Glossary:Item) during the reading phase, and consolidate knowledge by making item-only repetitions later in the day. In the end, sticking to [priorities](https://help.supermemo.org/wiki/Glossary:Priority), [auto-sort](https://help.supermemo.org/wiki/Glossary:Auto-sort), and [auto-postpone](https://help.supermemo.org/wiki/Glossary:Auto-postpone) will be the best least-biased long-term strategy
- **Fun is the key to success**: If your learning text is too "dry", not too meaningful, too wordy, etc. the fun of learning will drop. If learning is not enjoyable, it is less likely to be effective. If you dislike a specific article, perhaps a [Wikipedia replacement](http://en.wikipedia.org/) would be fun and more meaningful? Even if this is a bit longer, you can process it pretty fast with [incremental reading](https://help.supermemo.org/wiki/Glossary:Incremental_reading), illustrate with pictures, and enjoy the process
- **Nurse your hunger for knowledge**: You have to find the clear-cut link between knowledge and the value it brings to life. The hunger for knowledge grows as you get more educated (the more you know the more you know you don't know). So there is an excellent remedy for poor motivation: learn more and see how it can impact your and others' life
- **You determine the speed of learning in [incremental reading](https://help.supermemo.org/wiki/Glossary:Incremental_reading)!** You can determine the frequency of presentation of [topics](https://help.supermemo.org/wiki/Glossary:Topic) (e.g. using [A-Factors](https://help.supermemo.org/wiki/Glossary:A-Factor), [priorities](https://help.supermemo.org/wiki/Glossary:Priority), **[Mercy](https://help.supermemo.org/wiki/Mercy)**, etc.). You can determine the level of [retention](https://help.supermemo.org/wiki/Glossary:Retention) for [items](https://help.supermemo.org/wiki/Glossary:Item) (e.g. with the [forgetting index](https://help.supermemo.org/wiki/Glossary:Forgetting_index), [priorities](https://help.supermemo.org/wiki/Glossary:Priority), [auto-postpone](https://help.supermemo.org/wiki/Glossary:Auto-postpone), etc.). You can execute forced ahead-of-time review of any material (see: [Subset review](https://help.supermemo.org/wiki/Subset_review))
- **You MUST NOT memorize material that you do not understand!** There is some hope that by doing more learning in other areas you will at some point understand. It is far more likely though that you will build up frustration with [items](https://help.supermemo.org/wiki/Glossary:Item) that mean little. If you do not understand a term or concept, you need to dig deep into why. Is it terminology? This can be easily investigated and fixed. Or is it a problem with the material itself? Perhaps you can find an alternative on the net? Perhaps you can find a nice picture on the net to illustrate the [item](https://help.supermemo.org/wiki/Glossary:Item)? Obviously, each little investigation takes time, but it is better to master 10-20% of the material well, that to cram an encyclopedia without comprehension. Even if you fail an exam, those 10% can be useful in the future (e.g. if you retake the exam). In general, schools load more than students can master and this leads to lots of stress and frustration. By choosing SuperMemo, you have already made the first good step. Now you need to make order in the process and think carefully about your best long-term strategy. Comprehension is the key to success!
- If you want to grade an [item](https://help.supermemo.org/wiki/Glossary:Item) **Null** or **Bad**, press *0* or *1* respectively
- SuperMemo is not yet equipped with tools to help you efficiently use your knowledge for good causes. It will boost your knowledge but... you must be vigilant: **Do not spend your time on gaining knowledge for the knowledge sake! Think applicability!** Luckily, as your knowledge grows, so does your ability to use it efficiently

#### Re-evaluation of items

You should remember that all [items](https://help.supermemo.org/wiki/Glossary:Item) introduced into your learning process require endless attention in reference to their applicability, formulation, importance, logic, etc. In a well-planned learning process, it should not be necessary to review [items](https://help.supermemo.org/wiki/Glossary:Item) in the periods between individual repetitions. However, when an [item](https://help.supermemo.org/wiki/Glossary:Item) comes up for a repetition, you should make a quick and nearly instinctive assessment of the following:

1. *Do I really need this item?*
2. *What is the honest [priority](https://help.supermemo.org/wiki/Glossary:Priority) of this item in the entire spectrum of my (desired) knowledge?*
3. *Is this item difficult to remember? If so, why?*
4. *Is it factually correct?*
5. *Is it as simple and clear as it could be?*
6. *Do I really need to know it now?*
7. *Do you need supplementary knowledge to understand all ramifications of the item?*

Here are some typical actions you will take depending on the answer to the above questions:

1. **edit** the item. You will use keys such as *Q*, *A*, or *E* to enter a desired text field and edit it. In more complex [items](https://help.supermemo.org/wiki/Glossary:Item) you will use *Ctrl+T* to circle between [components](https://help.supermemo.org/wiki/Glossary:Component), *Alt+click* to switch a component between [editing](https://help.supermemo.org/wiki/Glossary:Editing_mode) and [dragging](https://help.supermemo.org/wiki/Glossary:Dragging_mode) modes, or *Ctrl+E* to enter the [editing mode](https://help.supermemo.org/wiki/Glossary:Editing_mode)
2. **de-prioritize** the item. For [items](https://help.supermemo.org/wiki/Glossary:Item) that are not important enough, or you are not sure are important enough, use *Alt+P* and reduce their [priority](https://help.supermemo.org/wiki/Glossary:Priority). You can also use *Ctrl+Shift+Down arrow* for minor deprioritizations
3. **reschedule** the item. If you know the item well or for some reason want to manually increase (or decrease) the length of the inter-repetition [interval](https://help.supermemo.org/wiki/Glossary:Interval), press *Ctrl+Shift+R* to select the date of the next repetition
4. **dismiss** the item. If you are sure you are not likely to need the item in the future, but you would like to keep it in your [collection](https://help.supermemo.org/wiki/Glossary:Collection) for reference or archival purposes, press *Ctrl+D*. [Dismissed items](https://help.supermemo.org/wiki/Glossary:Dismissed_element) are removed from the learning process
5. **delete** the item. The key *Del* is very useful in cleaning your [collection](https://help.supermemo.org/wiki/Glossary:Collection) from garbage that results from your desire to know more than your memory can hold. In the [editing mode](https://help.supermemo.org/wiki/Glossary:Editing_mode) or in spelling [items](https://help.supermemo.org/wiki/Glossary:Item) (i.e. at times when *Del* plays text editing functions), you may need to use *Ctrl+Shift+Del* instead. Please note that deleting an [element](https://help.supermemo.org/wiki/Glossary:Element) in SuperMemo will delete all its [children](https://help.supermemo.org/wiki/Glossary:Child)! You may therefore wish to learn to always use safer **Done** (*Ctrl+Shift+Enter*) instead
6. **delay** or **forget** the item. If you think the item is too difficult at the moment, you can postpone learning it. For this purpose, choose *Ctrl+J* to set a new [interval](https://help.supermemo.org/wiki/Glossary:Interval) or use **Forget** to transfer the item to the [pending queue](https://help.supermemo.org/wiki/Glossary:Pending_queue). This will give you some time to import some supplementary material that will help you understand the item

### Formulation

- **Use minimum information principle** which says that simple [elements](https://help.supermemo.org/wiki/Glossary:Element) formulated for [active recall](https://help.supermemo.org/wiki/Glossary:Active_recall) bring much better learning results than complex elements. This holds true even though one complex [element](https://help.supermemo.org/wiki/Glossary:Element) may be equivalent to a large number of simpler elements. See: [Minimum information principle](https://help.supermemo.org/wiki/Incremental_learning#Minimum_information_principle).
- Some information may be presented as a list. Lists should be avoided. However, some are inevitable (e.g. list of nerves, list of tributaries, list of EU admissions, etc.). If you need to memorize lists, use mnemonic techniques and try to [mimic real life situations to combat memory interference](https://help.supermemo.org/wiki/Incremental_learning#Mimic_real_life_situations_to_combat_memory_interference). See also: [Learning lists](https://help.supermemo.org/wiki/Incremental_learning#Learning_lists)
- The way you ask the question in SuperMemo may differ from the way your life asks you the same question. In other words, you may store some material in SuperMemo, but a real-life situation will trick you into being unable to recall it. In other words, you need to properly formulate the material to maximize its recall in all potential contexts
- Remember about the universality of memorized rules. For example, it is better to learn a universal mathematical formula than just the examples of its use. Examples can be used to emphasize applicability in various contexts
- You can use **Parse HTML** (*Ctrl+Shift+1*) to convert selected HTML code into formatting (e.g. try inserting <hr> or <br> and parsing it with **Parse HTML**). You can also use this option to remove formatting (e.g. if you want to get rid of line breaks)
- You can edit your more elaborate texts using your favorite HTML editor. You need to associate that editor with the filename extension **.HTM*. For example, if you associate [Microsoft Expression Web](http://www.microsoft.com/en-us/download/details.aspx?id=36179) (free) with *.HTM, you can edit your texts by just pressing *Ctrl+F9*. If you would rather leave your associations unchanged, you can use *F9* to view the file in Internet Explorer, and choose **File : Edit with Microsoft Expression Web** (that menu item is added to Internet Explorer by Expression Web). For more see: [Open HTML files in the default HTML editor](http://supermemopedia.com/wiki/Open_HTML_files_in_the_default_HTML_editor)
- Background color styles are used in [incremental reading](https://help.supermemo.org/wiki/Glossary:Incremental_reading) to preserve the original font used in documents. However, for this to work you must uncheck the following option in your Internet Explorer: **Tools : Internet options : General : Accessibility : Formatting : Ignore colors specified on webpages**

To learn more about efficient formulation read: [Effective learning: 20 rules of formulating knowledge](http://www.super-memory.com/articles/20rules.htm)

### Pictures

- **Important pictures should be kept in image [components](https://help.supermemo.org/wiki/Glossary:Component) (not inside HTML texts)**. Use *Ctrl+V* or *Shift+Ins* to paste a picture from the clipboard. You can paste the picture to a new [element](https://help.supermemo.org/wiki/Glossary:Element) or to an image [component](https://help.supermemo.org/wiki/Glossary:Component). Do not paste pictures to HTML. Having pictures pasted into an image [component](https://help.supermemo.org/wiki/Glossary:Component) makes it easy to resize, tile, fit, or move the image, as well as to change its attributes such as stretch, transparency, display time (e.g. at answer time only), etc. Pictures pasted or imported to image [components](https://help.supermemo.org/wiki/Glossary:Component) are stored in the image [registry](https://help.supermemo.org/wiki/Glossary:Registry) and can be searched for by their name. They can be reused in many [elements](https://help.supermemo.org/wiki/Glossary:Element). They are automatically used to illustrate all [extracts](https://help.supermemo.org/wiki/Glossary:Extract) and [clozes](https://help.supermemo.org/wiki/Glossary:Cloze_deletion) generated from the article that holds the picture. They cannot be easily lost when editing texts, etc. [HTML components](https://help.supermemo.org/wiki/HTML_component) can keep remote pictures stored on the web but, naturally, you will lose them once the picture is removed from the remote server

- Use **Download** with **Insert** or **Localize** in **[Download images](https://help.supermemo.org/wiki/Component_menu#Download_images)** on the [component menu](https://help.supermemo.org/wiki/Component_menu) (*Ctrl+F8*) to transfer remote pictures to your hard disk

- Use **Rename (member)** (*Alt+R*) to give pictures meaningful names for an easy search in the image [registry](https://help.supermemo.org/wiki/Glossary:Registry)

- To search for a picture, use

   

  [Search](https://help.supermemo.org/wiki/Search_menu) : [Find elements](https://help.supermemo.org/wiki/Find_elements)

   

  (

  Ctrl+F

  ). Alternatively, you can locate it via the image

   

  registry

   

  with:

  1. **[Search](https://help.supermemo.org/wiki/Search_menu) : [Images](https://help.supermemo.org/wiki/Search_menu#Images)** (to open the image [registry](https://help.supermemo.org/wiki/Glossary:Registry)), and
  2. *Ctrl+S* to search the registry (same as **[Search](https://help.supermemo.org/wiki/Registry_menu#Search) : Find texts** on the [registry menu](https://help.supermemo.org/wiki/Registry_menu))

- If you want a picture to be part of the answer (i.e. not visible at question time), mark it with **[Answer](https://help.supermemo.org/wiki/Component_menu#Answer)** on the image [component menu](https://help.supermemo.org/wiki/Component_menu)

To learn more about using pictures, see: [Visual learning](https://help.supermemo.org/wiki/Visual_learning)

### References

See: [Hints for using references](https://help.supermemo.org/wiki/References#Reference_system_highlights)

### Your own discoveries

In incremental learning, you will quickly discover why some of your own ideas about the learning process might not be optimum. Here are some things that you will discover on your own within the first 2-3 months of intense incremental learning:

- recognition is good for your exam, but recall is vital for your professional skills in the long-term
- manually organizing the timing of review is not what suits your memory best; it is actually quite the opposite to the idea of SuperMemo, which says that you review the material at moments that help stabilize memories
- manually organizing the order of review is not what suits your memory best (even though [subset review](https://help.supermemo.org/wiki/Subset_review) is a very useful tool in SuperMemo when preparing for an exam)
- for beginners, traditional learning might be superior to SuperMemo in a very short-term (perhaps up to 1-2 months) because of the steep learning curve. You need to learn the toolset of [incremental reading](https://help.supermemo.org/wiki/Glossary:Incremental_reading) before you can reap the benefits (unless you employ simple Q&A learning when SuperMemo might be superior even within a week's perspective)
- you may reach 95% recall within 1-2 weeks on condition that you do not [postpone](https://help.supermemo.org/wiki/Postpone) your review. However, if you dump 1,000 pages of [topics](https://help.supermemo.org/wiki/Glossary:Topic) into the process at once, you will simply not manage to review all that material as scheduled by SuperMemo, and your [retention](https://help.supermemo.org/wiki/Glossary:Retention) might hover around 60-80% depending on how much time you invested in making repetitions
- once SuperMemo learns a bit about your memory and habits (1-3 weeks), you will oscillate around 95% recall as of the first repetition (if you do not [delay](https://help.supermemo.org/wiki/Postpone), and if you stick to the [rules of formulating knowledge](http://www.super-memory.com/articles/20rules.htm))
- you will quickly discover that multiple [cloze deletions](https://help.supermemo.org/wiki/Glossary:Cloze_deletion) on a single paragraph are not a good idea (e.g. compare the [measured forgetting index](https://help.supermemo.org/wiki/Glossary:Measured_forgetting_index) with [items](https://help.supermemo.org/wiki/Glossary:Item) that have the same cloze keywords separated, or just see how thus gained knowledge works in practice)
- you can look at learning parameters in SuperMemo to see how different approaches to learning affect your progress
